[package]
name = "adv_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde = {version = "1.0" , features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
rand = "0.8"
base64 = "0.21"
ed25519-dalek = "1.0"
tokio = { version = "1", features = ["full"] }
sled = "0.34"
hex = "0.4"
warp = "0.3"
